version: '3.1'

services: 

  localstack:
    image: localstack/localstack:0.14.1
    environment: 
      - AWS_DEFAULT_REGION=us-east-1
      - SERVICES=lambda,s3,sqs,sns,dynamodb,sts,kms
      - DEBUG=1
    ports: 
      - '4566-4583:4566-4583'
    volumes: 
      - "${TEMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"